from fastapi import FastAPI, Depends, HTTPException, Request
from fastapi.responses import JSONResponse
from app.config import settings
from app.auth import verify_api_key, get_user_id
from app.rate_limiter import check_rate_limit, get_rate_limit_status
from app.cost_guard import check_budget, add_cost, get_budget_status
from .agent import graph
import json
import time
import logging

# Configure logging
logging.basicConfig(level=settings.LOG_LEVEL.upper())
logger = logging.getLogger(__name__)

app = FastAPI(title="TravelBuddy Production Agent", version="1.0.0")


@app.get("/health")
def health():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "timestamp": time.time(),
        "service": "travelbuddy-agent",
        "version": "1.0.0"
    }


@app.get("/ready")
def ready():
    """Readiness check - verifies dependencies."""
    checks = {
        "redis": False,
        "agent_graph": False
    }
    
    # Check Redis connection
    try:
        from app.rate_limiter import r
        if r is not None:
            r.ping()
            checks["redis"] = True
    except Exception:
        checks["redis"] = False
    
    # Check if agent graph is loaded
    try:
        if graph is not None:
            checks["agent_graph"] = True
    except Exception:
        checks["agent_graph"] = False
    
    if all(checks.values()):
        return {
            "status": "ready",
            "checks": checks,
            "timestamp": time.time()
        }
    else:
        raise HTTPException(
            status_code=503,
            detail={
                "status": "not_ready",
                "checks": checks,
                "timestamp": time.time()
            }
        )


@app.post("/ask")
async def ask(
    request: Request,
    user_id: str = Depends(verify_api_key),
    _rate_limit: None = Depends(check_rate_limit),
    _budget_check: None = Depends(check_budget)
):
    """
    Main endpoint for agent queries.
    Implements ReAct pattern with rate limiting and cost guard.
    """
    start_time = time.time()
    
    # Extract question from request body
    try:
        body = await request.json()
        question = body.get("question", "")
        # Optionally allow overriding user_id from body
        # user_id = body.get("user_id", user_id)
    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Invalid JSON in request body"
        )
    
    if not question:
        raise HTTPException(
            status_code=400,
            detail="Missing 'question' field in request body"
        )
    
    # Initialize state with the question
    state = {"messages": [("human", question)]}
    
    try:
        # Execute the agent graph
        logger.info(f"Processing question for user {user_id}: {question[:100]}...")
        
        # Stream through graph to capture execution
        final_state = None
        for output in graph.stream(state):
            for node_name, node_update in output.items():
                # Update state with node output
                state["messages"].extend(node_update.get("messages", []))
                final_state = output
        
        # Extract final answer
        final_messages = final_state.get("agent", {}).get("messages", []) if final_state else []
        if not final_messages:
            # Fallback to last message in state
            final_messages = state["messages"][-1:] if state["messages"] else []
        
        if not final_messages:
            raise HTTPException(
                status_code=500,
                detail="No response generated by agent"
            )
        
        final_message = final_messages[-1]
        answer = getattr(final_message, 'content', str(final_message))
        
        # Calculate processing time
        processing_time = time.time() - start_time
        
        # Track cost (approximate)
        try:
            add_cost(user_id, COST_PER_REQUEST)
        except Exception as e:
            logger.warning(f"Failed to track cost: {e}")
        
        # Get updated status
        rate_status = get_rate_limit_status(user_id)
        budget_status = get_budget_status(user_id)
        
        logger.info(f"Completed request for user {user_id} in {processing_time:.2f}s")
        
        return {
            "answer": answer,
            "user_id": user_id,
            "processing_time_seconds": round(processing_time, 2),
            "rate_limit": rate_status,
            "budget": budget_status,
            "timestamp": time.time()
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing request: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Internal server error: {str(e)}"
        )


@app.get("/status/{user_id}")
def get_user_status(
    user_id: str,
    _: str = Depends(verify_api_key)  # Require auth to view status
):
    """
    Get current rate limit and budget status for a user.
    """
    rate_status = get_rate_limit_status(user_id)
    budget_status = get_budget_status(user_id)
    
    return {
        "user_id": user_id,
        "rate_limit": rate_status,
        "budget": budget_status,
        "timestamp": time.time()
    }


# Exception handlers
@app.exception_handler(404)
async def not_found_handler(request: Request, exc: HTTPException):
    return JSONResponse(
        status_code=404,
        content={"error": "Endpoint not found", "path": str(request.url.path)}
    )


@app.exception_handler(500)
async def internal_error_handler(request: Request, exc: HTTPException):
    return JSONResponse(
        status_code=500,
        content={"error": "Internal server error", "message": "Please try again later"}
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        app, 
        host=settings.HOST, 
        port=settings.PORT,
        log_level=settings.LOG_LEVEL.lower()
    )